CREATE TABLE CITY(
    CITY_ID  SERIAL PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL
);

CREATE TABLE REALTY(
    REALTY_ID  SERIAL PRIMARY KEY,
    LATITUDE   NUMERIC(14, 12) NOT NULL,
    LONGITUDE  NUMERIC(15, 12) NOT NULL,
    GEOHASH    VARCHAR(10) NOT NULL,
    PRICE      NUMERIC(19, 2) NOT NULL,
    CITY_ID    INTEGER NOT NULL REFERENCES CITY(CITY_ID)
);

CREATE INDEX IDX_REALTY_1 ON REALTY(LATITUDE, LONGITUDE, GEOHASH, CITY_ID);
